application.nearby.search.url=https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=
application.place.details.url=https://maps.googleapis.com/maps/api/place/details/json?placeid=
application.place.photo.url=https://maps.googleapis.com/maps/api/place/photo?maxwidth=500&photoreference=
application.radius=5000
application.type=hindu_temple|place_of_worship
application.key=AIzaSyCGQXxk8OuozrZcbz_ublcvQP6r12d1oGs